src/objects/ACMN_Error_Log__c.object
<CustomObject>
    <description>Used to store error logs outside of debug</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Stores the Apex Class name if applicable</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Stores the error message and/or stack trace</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Exact date time the error occured</description>
        <label>Log Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Other_Details__c</fullName>
        <description>Store any additional information if applicable.  Examples: Detailed stack trace, API Endpoint URI, etc.</description>
        <label>Other Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>ACMN Error Log</label>
    <nameField>
        <displayFormat>err-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACMN Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AcuOrgUtil/src/objects/ACMN_Error_Log__c.object
    <fields>
        <fullName>Running_User__c</fullName>
        <description>Salesforce ID of the running user that triggered the error.</description>
        <inlineHelpText>Salesforce ID of the running user that triggered the error.</inlineHelpText>
        <label>Running User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>

AcuOrgUtil/src/objects/ACMN_Error_Log__c.object
    <fields>
        <fullName>StackTraceString__c</fullName>
        <description>Store stacktrace if error logger processed an exception.</description>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>

src/objects/ACMN_Error_Log_PE__e.object
<CustomObject>
    <description>Creates an error log record based on parameters entered</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Date_Time__c</fullName>
        <label>Log Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Other_Details__c</fullName>
        <label>Other Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Running_User_ID__c</fullName>
        <description>Salesforce ID of the running user that triggered the error.</description>
        <label>Running User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StackTraceString__c</fullName>
        <label>Stacktrace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>ACMN Error Log</label>
    <pluralLabel>ACMN Error Logs</pluralLabel>
</CustomObject>

src/classes/ACMN_Logger_Service_PE.cls
/**
 * Created by gtandeciarz on 7/20/18.
 *
 * Default service implementation example used to store records via Salesforce Platform Events.
 * Create your own services and bind them via the Custom Metadata Type record
 */

public class ACMN_Logger_Service_PE extends ACMN_Error_Logger.Service{

    //default usage publishes to the platform events message bus
    public override void processRecords( List<String> recordsAsJSON ) {
        List<ACMN_Error_Log_PE__e> pes = new List<ACMN_Error_Log_PE__e>();
        for(String record : recordsAsJSON){
            ACMN_LogRecord rec = (ACMN_LogRecord)JSON.deserialize(record, ACMN_LogRecord.class);
            pes.add(rec.getPlatformEventObject());
        }
        publishPE(pes);
    }

    @TestVisible
    private void publishPE(List<ACMN_Error_Log_PE__e> pes){
        if(Schema.SObjectType.ACMN_Error_Log_PE__e.isCreateable() && !pes.isEmpty()){
            ACMN_Error_Logger.processSaveResults(EventBus.publish(pes));
        }
    }

    //Used by the Platform Events trigger to save records to the Salesforce database
    public static void savePlatformEventsAsLogs(List<ACMN_Error_Log_PE__e> events){
        List<ACMN_Error_Log__c> records = new List<ACMN_Error_Log__c>();
        for(ACMN_Error_Log_PE__e pe : events){
            records.add(new ACMN_Error_Log__c(
                    Error_Message__c = pe.Error_Message__c,
                    Class_Name__c = pe.Class_Name__c,
                    Other_Details__c = pe.Other_Details__c,
                    StackTraceString__c = pe.StackTraceString__c,
                    Log_Date_Time__c = pe.Log_Date_Time__c,
                    Running_User__c = pe.Running_User_ID__c
            ));
        }
        ACMN_Error_Logger.saveToSalesforce(records, 'ACMN_Logger_Service_PE');
    }
}