src/objects/ACMN_Error_Log__c.object
<CustomObject>
    <description>Used to store error logs outside of debug</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Stores the Apex Class name if applicable</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Stores the error message and/or stack trace</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Exact date time the error occured</description>
        <label>Log Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Other_Details__c</fullName>
        <description>Store any additional information if applicable.  Examples: Detailed stack trace, API Endpoint URI, etc.</description>
        <label>Other Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>ACMN Error Log</label>
    <nameField>
        <displayFormat>err-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACMN Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AcuOrgUtil/src/objects/ACMN_Error_Log__c.object
    <fields>
        <fullName>StackTraceString__c</fullName>
        <description>Store stacktrace if error logger processed an exception.</description>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>

src/objects/ACMN_Error_Log_PE__e.object
<CustomObject>
    <description>Creates an error log record based on parameters entered</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Date_Time__c</fullName>
        <label>Log Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Other_Details__c</fullName>
        <label>Other Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StackTraceString__c</fullName>
        <label>Stacktrace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>ACMN Error Log</label>
    <pluralLabel>ACMN Error Logs</pluralLabel>
</CustomObject>

src/classes/ACMN_LogRecord.cls
/**
 * Created by gtandeciarz on 7/10/18.
 */

public with sharing class ACMN_LogRecord implements Comparable{
    public String message {get;set;}
    public String className {get;set;}
    public String otherDetails {get;set;}
    public String stacktrace {get;set;}
    public DateTime logDate {get;set;}
    public ACMN_LogRecord(Exception ex){
        this.message = ex.getMessage();
        this.otherDetails = 'Type Name: ' +  ex.getTypeName();
        this.stacktrace = ex.getStackTraceString();
        this.logDate = System.now();
    }
    public ACMN_LogRecord(String msg){
        this.message = msg;
        this.logDate = System.now();
    }
    public ACMN_Error_Log__c getSObject(){
        ACMN_Error_Log__c log = new ACMN_Error_Log__c();
        log.Error_Message__c = this.message;
        log.Class_Name__c = this.className;
        log.Other_Details__c = this.otherDetails;
        log.StackTraceString__c = this.stacktrace;
        log.Log_Date_Time__c = this.logDate;
        return log;
    }
    public ACMN_Error_Log_PE__e getPlatformEventObject(){
        ACMN_Error_Log_PE__e log = new ACMN_Error_Log_PE__e();
        log.Error_Message__c = this.message;
        log.Class_Name__c = this.className;
        log.Other_Details__c = this.otherDetails;
        log.StackTraceString__c = this.stacktrace;
        log.Log_Date_Time__c = this.logDate;
        return log;
    }

    public Integer compareTo( Object objToCompare ) {
        ACMN_LogRecord obj2 = (ACMN_LogRecord)objToCompare;
        if(logDate > obj2.logDate) return 1;
        if(logDate < obj2.logDate) return -1;
        return 0;
    }
}